### ISSUE TITLE
Standard fields cannot be customized with mappings

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-salesforce#11]
Add an outbound mapping for `{{lead.state.name}}` => `lead.state` then submit a lead where `state=TX`. Instead of sending `state=Texas` the integration will send `state=TX`.

**Comment by cgrayson** [comment]
After further discussion, the problem is because the `state` request variable is [defined as a `state` type](https://github.com/activeprospect/leadconduit-integration-salesforce/blob/master/src/web_to_lead.coffee#L67). That's causing the handler to take the state _name string_ this customer wants to send to Salesforce (e.g., "Texas") and _create_ a `state` type object from it. 

Then when the request is created, that variable is [getting `valueOf()`'d](https://github.com/activeprospect/leadconduit-integration-salesforce/blob/master/src/web_to_lead.coffee#L22), which for `state` types yields the two-letter abbreviation (e.g., "TX"). 

The solution we came to is to change the `state` request variable to type `string`. In conjunction with a change to the `leadconduit-types` module, that will allow users to map this data however they need it.

cf. [this ticket](https://activeprospect.zendesk.com/agent/tickets/8810).
